### ISSUE TITLE
Can't remove custom sounds with long URLs

### ISSUE THREAD

**Issue by HeyMyian** [bobmitch/ps2announcer#15]
![2020-09-25___10-08-34](https://user-images.githubusercontent.com/60368695/94242999-1e8b5580-ff17-11ea-8fe1-78703f2b541c.jpg)

**Comment by bobmitch** [comment]
UX question - what would be better: Letting the 'card' scroll if there's wider content, or try and extend the bulma css to constrain the 'tags' and truncate content with ellipsis?
1st way is a bit easier, but 2nd way is doable to - just need your opinion.

**Comment by HeyMyian** [comment]
My gut feeling says I'd prefer to put ellipsis in the middle (or even beginning?) of the URL, so that the **file name** and the "playback" and "delete" buttons are always visible at the end. Upon mouseover it may display the full URL.

I wouldn't like 1st way too much, but for the sake of functionality it doesn't matter.

**Comment by bobmitch** [comment]
Uploaded a change (haven't pushed to repo yet), so you should see it on the site:

![image](https://user-images.githubusercontent.com/23583515/94294064-41286900-ff2d-11ea-8cc9-de2d8031fad4.png)

**Comment by HeyMyian** [comment]
I'm kind of not convinced by it, so apologies for the suggestion and I'm nitpicking here. Perhaps the most important information is the file name, just like how the default audio files are displayed. So I personally (because crap like that is fun to me!) would try with regexing away everything before the last `/` and put the complete URL in the title tag instead. If you decide to go down that route, Bulma has a sweet [tooltip extension](https://wikiki.github.io/elements/tooltip/).

There is also these display issues, depending on browser width and column size:
Separated buttons:
![2020-09-25___19-02-35](https://user-images.githubusercontent.com/60368695/94295645-d6ddeb80-ff61-11ea-8d66-a3e5fc74fe16.jpg)
Weird truncation where there would be enough space for the rest:
![2020-09-25___19-02-19](https://user-images.githubusercontent.com/60368695/94295658-dba29f80-ff61-11ea-8d55-64fe71c93b38.jpg)

**Comment by bobmitch** [comment]
Filename only being displayed. How do you think we should handle still-too-long filenames?

Tooltips are in place, but the css solution requires no overflow on containers to be visible like this:

![image](https://user-images.githubusercontent.com/23583515/94305140-bc464b00-ff3e-11ea-8ea2-54cff4b566a0.png)

or we can have scrolling and it looks like this, but tooltips are also then constrained by the container: 

![image](https://user-images.githubusercontent.com/23583515/94305232-d97b1980-ff3e-11ea-8f41-ba9ef26382a4.png)

![image](https://user-images.githubusercontent.com/23583515/94305304-f283ca80-ff3e-11ea-8daf-43da4fcc3206.png)

 ...or do we then just ellipsis and cutoff the end of the filename rather than the start of the url?

**Comment by HeyMyian** [comment]
Not a fan of the scrolly, but an ellipsis at the end seems to be nice.

(Apparently the URL needs to go into the `data-tooltip` (with the extension) **or** the `title`, not both.)

**Comment by bobmitch** [comment]
Dropped the nice tooltip. It doesn't play well with hiding the overflow on the filename span - which is necessary to do the cut-off ellipses. Will keep the title attribute, as it's an accessible tooltip in reality. 

Super long filenames will end up looking like this: 

![image](https://user-images.githubusercontent.com/23583515/94328794-6d6ed480-ff83-11ea-9b55-6dc0e800f183.png)
