### ISSUE TITLE
Feature request (stretch goal?): custom per-weapon triggers

### ISSUE THREAD

**Issue by HeyMyian** [bobmitch/ps2announcer#20]
Just babbling ideas ok. Whether or not they are feasible or you want them in your tool is your prerogative.

I would like to see triggers on kill/death for my favorite meme weapons (Amaterasu, CandyCannon, Flare Guns, ...). Instead of hard-coding these (easier option?), I'm envisioning the user being able to create and delete dynamic triggers ("cards" in your Bulma syntax) with these information:

- weapon (selecting from a predefined list of weapons fetched from the API)
- trigger on kill or on death
- sound file

**Comment by bobmitch** [comment]
Babbling is encouraged.

I thought about having some sort of 'logic builder' for crafting all the triggers, but the UI/UX becomes the project instead of making pew pew noises ;) and becomes more like _real_ work. Then I thought about making a scripting language to allow this instead, but then I remembered: javascript _is_ a scripting language, and so that's how I define everything now.   

**However**, your limited use case _is_ feasible, and probably fun to implement too. Might get a little tricky managing exporting soundpacks, because realistically these custom triggers should be able to be exported (so, for example, you can stream from another location without having to set up _everything_ again).

I might have to make trigger priorities user-facing options as well so you can decide which audio gets triggered when multiple events are true. Also might have to look into making an audio queue, so that if a trigger is classes as 'not interruptable' the next trigger waits until the previous is finished before completing - some of this is already in the objects as a value, just not doing anything with it yet.

So, I'll give it a shot - made a new branch called [customtriggers](https://github.com/bobmitch/ps2announcer/tree/customtriggers) - [live testing](https://bobmitch.com/ps2test/) up here.

**Comment by bobmitch** [comment]
Got things kind of working I think.  To add custom weapon triggers click 'add custom weapon trigger' on the manage audio screen: 

![image](https://user-images.githubusercontent.com/23583515/94328607-dbb29780-ff81-11ea-8b17-9ed4fe282e2f.png)

This will allow you to add your own triggers based on a weapon of your choice (kill or death). Might have it play a default audio if one's not assigned, not sure about that yet. The custom triggers are saved/exported along with the regular triggers too, so 'packs' can be made and shared/backed up easily.

I haven't tested this _at all_ yet - lol - but I'll add a streamer and test live some before I crash tonight maybe.

![image](https://user-images.githubusercontent.com/23583515/94328734-da359f00-ff82-11ea-9518-b226a886cb06.png)

Custom triggers can be edited/deleted using the new buttons shown above - audio files themselves are handled exactly as with built-in triggers.

**Comment by HeyMyian** [comment]
Sweet! 😄

ohmigod the weapon names in PlanetSide 2 are awful. I guess the list should be sorted alphabetically. In a perfect world, there'd be a live text search because heck who knows whatever numbers and letters some weapons are prefixed by, like, what

**Comment by bobmitch** [comment]
Dropped [slimselect ](https://github.com/brianvoe/slim-select) in - I've used it before and works well.

![image](https://user-images.githubusercontent.com/23583515/94341288-09293080-ffd6-11ea-9f3d-8cd35e5afd5a.png)

**Comment by bobmitch** [comment]
FYI - merged this branch into master and it's now on the main [url](https://bobmitch.com/ps2/)

**Comment by HeyMyian** [comment]
API is a troll. Scrolling through, I've found some entries that are rather questionably weapons:

- High-Capacity Fuel Tanks
- Quick-Recharge Fuel Tanks
- Bounty Contract
- External Afterburner Fuel Tanks 1-4
- External Fuel Tanks
- NC/VS/TR Turret Shield
- Nanite Healing Grenade
- Nanite Revive Grenade (I think these do 0 damage, opposed to flash nades etc.)

**Comment by bobmitch** [comment]
API is fine, it's a Bob issue. (Pretty safe to assume this 99% of time)

Added fuel tank, bounty and shield categories to blacklist for select list generation. All grenades are in same category regardless, so I _could_ blacklist individual ones, but I don't care enough. lol. You never know, DBG might make the healing nades do 1 tick of damage like the flashbangs one day - and I think that'd be cool. 🔢 

And **thanks** for helping make this better.

**Comment by bobmitch** [comment]
FYI, the API doesn't return separate entities as weapons - _**everything**_ in the game is just an item - boosts, camos, weapons, cosmetic items etc, so I just have to try and match up the categories where appropriate.
