### ISSUE TITLE
Re: server-side config

### ISSUE THREAD

**Issue by HeyMyian** [bobmitch/ps2announcer#38]
#28 This is a cool feature, thanks for implementing 😎 

One or two things:

- ~~Is it not possible anymore to load someone else's config into a personal WIP config? Since it disallows me from altering the "bobmitch" config without entering your password - but what if I really liked that config and wanted to alter it slightly for my own use? Am I overseeing something?~~ Edit: Oh, right, #29 I've read that one before having checked the closed issues and did not understand it. I understand now.

- UI-wise, it's a little clunky to have all the options (trigger on/off, "add custom soundfile", "change image") displayed in the UI, but practically unusable for people without the password. People should not be able to interact with things they will never be able to interact with.
My first thought is to initially hide all the customizing buttons from the UI, or switch them to something like "static" in Bulma. You already have this handy padlock icon in the Triggers Modal - upon clicking that, one would be prompted to enter the password for the current config which would unlock all the customizing buttons.

You think you're closing issues on me, I'll just open new ones 😄 Cheers.

**Comment by HeyMyian** [comment]
- Using special characters in the custom config name yields unexpected results. I don't know exactly what I expected. Names like "myianü" or "myian_" seem to default to a "no soundpack loaded" state, even when the informative popup says "Loaded bobmitch soundpack".

- I just claimed "null", not sure if I was supposed to be able to do that, because previously somewhere along my frantic clicking it somehow (can't reproduce the steps) redirected me to https://bobmitch.com/ps2/null

- Are you going to keep the names case-sensitive?

But I think you're working on it already anyway.

**Comment by bobmitch** [comment]
Clunky UI and me have a complicated history. :)  

I guess hiding the options until they have their own 'playground' make a lot of sense, so yeah, maybe hide everything until they are on their own space - if you want to play with another soundpack as a starting point, use the (not yet made) copy/migrate soundpack functionality.

I'll look more into the character thing - I know I'm doing some 'sanitizing', but linux should handle UTF8 filenames without a problem, I think it's maybe working, but not back into JS when it does the ajax request.... will do some investigation.

Null shouldn't be "easily" claimable, because it shouldn't send the request to claim unless the prompt returns a non-null/non-empty response. Will find the bug. :) 

Case sensitivity - is there a reason not to be case sensitive? People 'claiming' too similar names? UTF8 names have the same issue. It's not a big issue to make it insensitive, just curious if I'm missing something.

**Comment by HeyMyian** [comment]
> Case sensitivity

I don't have a big point here because I don't have any training in UX. But years and years of people citing their email addresses to me while emphasizing their Firstname.Lastname email address is spelled with uppercase letters has me burnt. The custom configs can be accessed by interacting with the URL, and nothing in a URL is case-sensitive so far. I was curious whether you had a reason for it.

**Comment by bobmitch** [comment]
Special characters update:

```php
if (ctype_alnum ($segments[0])) {
```

This happens early in the PHP, and basically checks that the first URL segment is all alphanumeric characters. Obviously not friendly to UTF8 characters, but it was the safest way for me to allow file creation (since I'm not using a database). Looking into allowing for alternative character sets safely.

**Comment by bobmitch** [comment]
URL's _are_ case sensitive (domains are not, for obvious reasons) - it's certain web servers (looking at you old version of IIS) that are/were not, usually Windows based ones. I'm happy to make this app case-insensitive - it does keep things cleaner.

**Comment by bobmitch** [comment]
You should now be able to claim your myianü URL. Please test / make a config change and let me know if works!

**Comment by HeyMyian** [comment]
Quick test, what works:

- `myianü`
- `myian_`
- `_myian`
- `myian` with a space as first character

Doesn't:
- `ümyian` --> loads `myian`

You can btw delete all these myian test configs except for the actual "myian", if you will.

I never intended to claim `myianü` btw, was merely checking possibilities.

**Comment by bobmitch** [comment]
I may go back to the alphanumeric test, and let people know (or just redirect to the homepage) if an 'improper' url is used. Those underscore ones didn't actually work and may have overwritten your myian one... :(

edit: Think I can just check if the 'filtered'/safe filename matches what the user submitted, then go ahead and allow it, otherwise redirect /warn.

**Comment by bobmitch** [comment]
Ok, it filters the passed URL segment and checks to see if the filtered version matches what the user passed - if it does, it will work fine. If not, it shows a warning that the user attempted to make an unsafe file.

Your ümyian, according to the filtering function I 'borrowed' is not a valid filename - this may be OS specific, but the function makes filenames that are universally valid for portability.

**Comment by bobmitch** [comment]
> * UI-wise, it's a little clunky to have all the options (trigger on/off, "add custom soundfile", "change image") displayed in the UI, but practically unusable for people without the password. People should not be able to interact with things they will never be able to interact with.
>   My first thought is to initially hide all the customizing buttons from the UI, or switch them to something like "static" in Bulma. You already have this handy padlock icon in the Triggers Modal - upon clicking that, one would be prompted to enter the password for the current config which would unlock all the customizing buttons.

![image](https://user-images.githubusercontent.com/23583515/95138922-61c89e00-0739-11eb-99dd-1aa635338bf2.png)

Must be unlocked before showing configurable elements other than volume.

> 
> You think you're closing issues on me, I'll just open new ones 😄 Cheers.

You're cheating by putting multiple issues in single comment threads! ;)

**Comment by HeyMyian** [comment]
> Those underscore ones didn't actually work and may have overwritten your myian one

The `myian` config is still intact. 👍 You can remove the ones I created with the numbers. Doesn't matter much if `myian` is lost either because I know my triggers by heart. 🙂 

> Must be unlocked before showing configurable elements other than volume.

Now you might be hiding too much information, for the purpose of being able to preview which images and sound files are assigned to each trigger. I have suggestions for the **view mode for people without passcode**:

- Hide all the trigger cards which are set to "off" in the first place (hide server-side or, if easier, with CSS)
- Remove the on/off radio inputs
- Remove the big green `+` button for adding custom audio files
- Remove the red `-` button for removing custom audio files (but perhaps allow for a different visual marker that a certain audio file is custom [in that vein, perhaps in general also allow the removal of the default audio files?])

> You're cheating by putting multiple issues in single comment threads! ;)

I'm not too familiar with the issue reporting on GitHub - should I be creating tiny issues each for every tiny problem? I mean I will absolutely do it.

**Comment by bobmitch** [comment]
> * Hide all the trigger cards which are set to "off" in the first place (hide server-side or, if easier, with CSS)
> * Remove the on/off radio inputs
> * Remove the big green `+` button for adding custom audio files
> * Remove the red `-` button for removing custom audio files (but perhaps allow for a different visual marker that a certain audio file is custom [in that vein, perhaps in general also allow the removal of the default audio files?])

Ok, I see - very reasonable suggestion. Should be do-able. Has to be done via js/css as the only time a pageload (PHP markup generation) happens is when switching soundpacks.

> > You're cheating by putting multiple issues in single comment threads! ;)
> 
> I'm not too familiar with the issue reporting on GitHub - should I be creating tiny issues each for every tiny problem? I mean I will absolutely do it.

Me neither, new-ish to github - though I'm very familiar with Basecamp at my job and fight constantly with account executives to make them submit 'todos' as individual items. It just makes tracking problems easy - but the bugs you find are usually related or fundamentally intertwined with each other, so it's fine.

For github, I think it makes it easier to relate issues with specific commits that should be done (and I don't because I'm old and lazy) for specific reasons and not just because.

**Comment by bobmitch** [comment]
Done, just need to style the 'custom' audio differently in the 'not authorized' view.
